DogaseverApp/DogaseverApp/Controllers/YaziController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DogaseverApp.Models;

namespace DogaseverApp.Controllers
{
    public class YaziController : Controller
    {
        private DogaseverDBContext db = new DogaseverDBContext();

        // GET: Yazi
        public ActionResult Index(string searchString)
        {
            var yazilar = from m in db.Yazilar
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                yazilar = yazilar.Where(s => s.Baslik.Contains(searchString));
            }

            return View(yazilar);

            //return View(db.Yazilar.ToList());
        }

        // GET: Yazi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yazi yazi = db.Yazilar.Find(id);
            if (yazi == null)
            {
                return HttpNotFound();
            }
            return View(yazi);
        }

        // GET: Yazi/Create
        public ActionResult Create()
        {
           
            return View();
        }

        // POST: Yazi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "YaziID,Baslik,Icerik,EklenmeTarihi")] Yazi yazi)
        {
            if (ModelState.IsValid)
            {          
                db.Yazilar.Add(yazi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(yazi);
        }

        // GET: Yazi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yazi yazi = db.Yazilar.Find(id);
            if (yazi == null)
            {
                return HttpNotFound();
            }
            return View(yazi);
        }

        // POST: Yazi/Edit/5        
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "YaziID,Baslik,Icerik,EklenmeTarihi")] Yazi yazi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yazi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yazi);
        }

        // GET: Yazi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Yazi yazi = db.Yazilar.Find(id);
            if (yazi == null)
            {
                return HttpNotFound();
            }
            return View(yazi);
        }

        // POST: Yazi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Yazi yazi = db.Yazilar.Find(id);
            db.Yazilar.Remove(yazi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DogaseverApp/DogaseverApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Doğaseverler Topluluğu</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Doğaseverler Kulübü", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>*@
                    <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                    <li>@Html.ActionLink("Yazılar", "Index", "Yazi")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Doğaseverler Topluluğu</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>